
baseURL = "https://blog.zrlab.org/"
title = "ZRLab"

copyright = '© 2019 - 2024 ZRLAB.ORG. [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).'

languageCode = "zh-Hans"
hasCJKLanguage = true
isCJKLanguage = true

disableHugoGeneratorInject = true

# 主题选择
theme = "consolex"

[params]
  description = "难道尽。"
  favicon = "/icons/icon.svg"
  mainSections = ["posts"]

  enableComments = true
  enableArtalk = true
  artalkServer = "artalk.zrlab.org"
  artalkSite = "ZRLab"

  [params.author]
    email = 'x@zrlab.org'
    name = 'Zmyeir'

  [[params.navlinks]]
  name = "links/"
  url = "links/"

  [[params.navlinks]]
  name = "categories/"
  url = "categories/"

  [[params.navlinks]]
  name = "tags/"
  url = "tags/"

  [[params.navlinks]]
  name = "about/"
  url = "about/"

[permalinks]
  posts = "posts/:slug/"

[pagination]
  disableAliases = false
  pagerSize = 6

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "onedark"
    lineNos = true
    lineNumbersInTable = false

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"

[services.rss]
  limit = 10

[build]
  writeStats = true


